version: "3.8"

services:
  app:
    build: .  # Build image từ Dockerfile trong thư mục hiện tại
    container_name: expense-management
    restart: always
    depends_on: []
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/expensemanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
